model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentInpaintDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    log_every_t: 100
    timesteps: 1000 # per overfittare tutti i livelli di rumore almeno 500 epoche
    first_stage_key: image
    cond_stage_key: masked_image # 4 channels
    cond_stage_trainable: false
    image_size: 128 #--> unused
    channels: 3
    concat_mode: true # there will be no context_dim specified in unet,
    finetune_keys_to_retain: null
    finetune_training_keys: null 
    monitor: val/loss_simple_ema

    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 7 # image, masked image, mask
        out_channels: 3 #FINAL IMAGE
        model_channels: 256
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        resblock_updown: true
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ddconfig:
          attn_type: none # concat mode
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity # NO TRAIN FOR AUTOENCODER
    cond_stage_config: __is_first_stage__